---
title: "My Projects"
format:
  html:
    theme: lux
    toc: true
---

## 📊 Data Analysis Projects

Here are some of the academic and personal projects I've worked on:

### Real Estate Trends in South Jamaica:
Built Power BI dashboards and conducted time series analysis in R.

South Jamaica, also known as "Southside," is a residential neighborhood in Queens, located south of downtown Jamaica. The dataset includes 13,860 observations, with 12,854 of them being residential type.

**What does this outcome mean?**

For real estate agents, these insights can help in planning marketing strategies and outreach efforts that align with market trends. Buyers and sellers can use the price prediction model and the forecast to assess market conditions. Developers and investors can use these insights to evaluate the financial health of the market before making investment decisions. Understanding seasonal variations can also assist local governments in making informed decisions about infrastructure and zoning.

You can download a PDF of my outcome here:

[📄 Download (PDF)](files/SouthJamaica.pdf){target="_blank"}


### Job Posting Insights: 
I also completed a group project with two teammates.

This report focus on the transformative impact of AI, salary disparities, and evolving employment patterns across various regions and industries. The website presents an in-depth exploration of job market data, including detailed insights into industry shifts, regional differences, and emerging skill demands. Additionally, we provide a thorough skill gap analysis, helping to bridge the divide between current team capabilities and the rapidly changing requirements of the IT job market. Join us in exploring how data-driven insights can shape career paths and workforce strategies in the modern job landscape.

  🔗 [View in Browser](https://cassielu0.github.io/AD688-employability-sp25A3-group2/)
